<?php

/**
 * @file
 * Hook implementations and related functions.
 */

/**
 * Implements hook_menu().
 */
function commerce_pos_currency_denomination_menu() {
  $items = array();

  $items['admin/commerce/config/pos/denomination'] = array(
    'title' => 'Configure Currency Denominations',
    'description' => 'Configure currency denominations for the cash count section.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_pos_currency_denomination_settings_form'),
    'access callback' => '_commerce_pos_access_check',
    'access arguments' => array('process commerce pos sales'),
    'file' => 'includes/commerce_pos_currency_denomination.admin.inc',
  );

  $items['admin/commerce/config/pos/denomination-type/add'] = array(
    'title' => 'Add Currency Denomination Type',
    'type' => MENU_VISIBLE_IN_BREADCRUMB,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_pos_currency_add_denomination_type_form'),
    'access callback' => '_commerce_pos_access_check',
    'access arguments' => array('process commerce pos sales'),
    'file' => 'includes/commerce_pos_currency_denomination.admin.inc',
  );

  $items['admin/commerce/config/pos/denomination-type/%/delete'] = array(
    'title' => 'Delete Currency Denomination Type',
    'page callback' => 'drupal_get_form',
    'type' => MENU_VISIBLE_IN_BREADCRUMB,
    'page arguments' => array(
      'commerce_pos_currency_delete_denomination_type_form',
      5
    ),
    'access callback' => '_commerce_pos_access_check',
    'access arguments' => array('process commerce pos sales'),
    'file' => 'includes/commerce_pos_currency_denomination.admin.inc',
  );

  $items['admin/commerce/config/pos/denomination-type/%/denomination/add'] = array(
    'title' => 'Add Denomination',
    'page callback' => 'drupal_get_form',
    'type' => MENU_VISIBLE_IN_BREADCRUMB,
    'page arguments' => array('commerce_pos_currency_add_denomination_form', 5),
    'access callback' => '_commerce_pos_access_check',
    'access arguments' => array('process commerce pos sales'),
    'file' => 'includes/commerce_pos_currency_denomination.admin.inc',
  );

  $items['admin/commerce/config/pos/denomination-type/%/denomination/view'] = array(
    'title' => 'View Denominations',
    'page callback' => 'commerce_pos_currency_view_denominations',
    'type' => MENU_VISIBLE_IN_BREADCRUMB,
    'page arguments' => array(5),
    'access callback' => '_commerce_pos_access_check',
    'access arguments' => array('process commerce pos sales'),
    'file' => 'includes/commerce_pos_currency_denomination.admin.inc',
  );

  $items['admin/commerce/config/pos/denomination-type/%/denomination/%/delete'] = array(
    'title' => 'Delete Denomination',
    'page callback' => 'drupal_get_form',
    'type' => MENU_VISIBLE_IN_BREADCRUMB,
    'page arguments' => array(
      'commerce_pos_currency_delete_denomination_form',
      5,
      7
    ),
    'access callback' => '_commerce_pos_access_check',
    'access arguments' => array('process commerce pos sales'),
    'file' => 'includes/commerce_pos_currency_denomination.admin.inc',
  );

  return $items;
}

/**
 * Returns all the denominations from the db for a currency code.
 *
 * @param array $currency_codes
 *   An array of currency codes.
 *
 * @return array
 *   Returns the denominations from the db keyed on the currency ID and
 *   denomination ID.
 */
function commerce_pos_currency_denomination_get_denominations(array $currency_codes = array()) {
  $denominations = array();

  // Let's first grab all the denominations under the given currency codes.
  $query = db_select('commerce_pos_currency_denomination', 'd');
  $query->fields('d');

  if ($currency_codes) {
    $currency_ids = commerce_pos_currency_denomination_get_currency_id($currency_codes);
    $query = $query->condition('currency_id', $currency_ids, 'IN');
  }
  $results = $query->execute();

  // Let's organize them by currency id and then, by denomination id.
  foreach ($results as $result) {
    $denominations[$result->currency_id][$result->denomination_id] = $result;
  }

  return $denominations;
}

/**
 * Returns the configured currency denomination types.
 *
 * @param array $currency_codes
 *   An array of currency codes.
 *
 * @return array
 *   Returns the denomination types from the db keyed on the currency ID.
 */
function commerce_pos_currency_denomination_get_currency_types(array $currency_codes = array()) {
  $denomination_types = array();

  $query = db_select('commerce_pos_currency_denomination_type', 't');
  $query = $query->fields('t');

  if ($currency_codes) {
    $query = $query->condition('currency_code', $currency_codes, 'IN');
  }

  $results = $query->execute();

  // Let's organize them by currency id.
  foreach ($results as $result) {
    $denomination_types[$result->currency_id] = $result;
  }

  return $denomination_types;
}

/**
 * Returns the configured currency denomination types.
 *
 * @param array $currency_ids
 *   An array of currency id.
 *
 * @return array
 *   Returns the denomination types from the db keyed on the currency ID.
 */
function commerce_pos_currency_denomination_get_currency_types_from_id(array $currency_ids = array()) {
  $denomination_types = array();

  $query = db_select('commerce_pos_currency_denomination_type', 't');
  $query = $query->fields('t');

  if ($currency_ids) {
    $query = $query->condition('currency_id', $currency_ids, 'IN');
  }

  $results = $query->execute();

  // Let's organize them by currency id.
  foreach ($results as $result) {
    $denomination_types[$result->currency_id] = $result;
  }

  return $denomination_types;
}

/**
 * Returns the currency ID given currency codes.
 *
 * @param array $currency_codes
 *   An array of currency codes.
 *
 * @return array
 *   Returns the currency info from the db keyed on the currency code.
 */
function commerce_pos_currency_denomination_get_currency_id(array $currency_codes) {
  $currency_ids = db_select('commerce_pos_currency_denomination_type', 't')
    ->fields('t', array('currency_code', 'currency_id'))
    ->condition('currency_code', $currency_codes, 'IN')
    ->execute()
    ->fetchAllKeyed(0, 1);

  return $currency_ids;
}

/**
 * Get the denomination info from the db given a denomination ID.
 *
 * @param int $denomination_id
 *   The denomination ID.
 *
 * @return array
 *   Returns the result from the db in an array keyed by the denomination ID.
 */
function commerce_pos_currency_denomination_get_denomination($denomination_id) {
  $denomination = array();

  // Let's first grab all the denominations under the given currency codes.
  $query = db_select('commerce_pos_currency_denomination', 'd');
  $query->fields('d');

  if ($denomination_id) {
    $query = $query->condition('denomination_id', $denomination_id);
  }
  $results = $query->execute();

  // Let's organize them by denomination id.
  foreach ($results as $result) {
    $denomination[$result->denomination_id] = $result;
  }

  return $denomination;
}

/**
 * Custom function to check if a denomination name already exists in the table.
 *
 * @param string $denomination_name
 *   The value to check for.
 *
 * @return mixed
 *   Returns 1 if it exists.
 */
function commerce_pos_currency_denomination_name_exists($denomination_name) {
  $custom_exists = db_query_range('SELECT 1 FROM {commerce_pos_currency_denomination} WHERE denomination_name = :name', 0, 1, array(':name' => $denomination_name))->fetchField();

  return $custom_exists;
}
