<?php

/**
 * @file
 * Contains commerce_pos.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_pos_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_pos module.
    case 'help.page.commerce_pos':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Commerce Point of Sale') . '</p>';
      return $output;

    default:
  }
}

/**
 * Form Alter hook.
 */
function commerce_pos_form_user_login_form_alter(&$form, FormStateInterface $form_state) {
  // Add our own custom submit handler for storing a token in the session.
  $form['#submit'][] = 'commerce_pos_user_log_form_submit';
}

/**
 * Submit handler for user_log_form.
 */
function commerce_pos_user_log_form_submit(&$form, FormStateInterface $form_state) {
}
