<?php

/**
 * @file
 * Main module file for the Commerce POS Report module.
 */

define('COMMERCE_POS_REPORT_JOURNAL_ROLE_DEFAULT_ITEMS_PER_PAGE', 25);
define('COMMERCE_POS_REPORT_SALES_REPORT_DEFAULT_ITEMS_PER_PAGE', 25);

/**
 * Implements hook_menu().
 */
function commerce_pos_report_menu() {
  $items['admin/commerce/pos/reports'] = array(
    'title' => 'Reports',
    'page callback' => 'commerce_pos_reports_page',
    'file' => 'includes/commerce_pos_report.pages.inc',
    'access arguments' => array('view commerce pos reports'),
  );
  $items['admin/commerce/pos/reports/end-of-day'] = array(
    'title' => 'End of Day Report',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_pos_report_end_of_day'),
    'file' => 'includes/commerce_pos_report.pages.inc',
    'access arguments' => array('view commerce pos reports'),
  );
  $items['admin/commerce/pos/reports/journal-role'] = array(
    'title' => 'Journal Role',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_pos_report_journal_role'),
    'file' => 'includes/commerce_pos_report.pages.inc',
    'access arguments' => array('view commerce pos reports'),
  );
  $items['admin/commerce/pos/reports/sales-report'] = array(
    'title' => 'Sales Report',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_pos_report_sales_report'),
    'file' => 'includes/commerce_pos_report.pages.inc',
    'access arguments' => array('view commerce pos reports'),
  );
  $items['admin/commerce/pos/end-of-day/print/%'] = array(
    'title' => 'Print Transaction Receipt',
    'page callback' => 'commerce_pos_report_receipt_print',
    'page arguments' => array(5),
    'access callback' => 'commerce_pos_receipt_print_access',
    'access arguments' => array(5),
    'file' => 'includes/commerce_pos_report.pages.inc',
  );
  $items['admin/commerce/pos/report/ajax/order-details/%commerce_order'] = array(
    'title' => 'Order details AJAX',
    'page callback' => 'commerce_pos_report_order_details_js',
    'page arguments' => array(6),
    'access arguments' => array('view commerce pos reports'),
    'delivery callback' => 'ajax_deliver',
    'file' => 'includes/commerce_pos_report.ajax.inc',
  );
  $items['admin/commerce/config/pos/reporting'] = array(
    'title' => 'Reporting',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_pos_report_settings'),
    'access arguments' => array('administer commerce pos report'),
    'file' => 'includes/commerce_pos_report.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function commerce_pos_report_theme($existing, $type, $theme, $path) {
  return array(
    'commerce_pos_report_receipt' => array(
      'template' => 'commerce-pos-report-receipt',
      'file' => 'commerce_pos_report.theme.inc',
      'path' => $path . '/theme',
      'variables' => array(
        'transaction' => NULL,
      ),
    ),
    'commerce_pos_report_end_of_day_result_table' => array(
      'render element' => 'form',
      'path' => $path . '/theme',
      'file' => 'commerce_pos_report.theme.inc',
    ),
    'commerce_pos_report_options' => array(
      'path' => $path . '/theme',
      'file' => 'commerce_pos_report.theme.inc',
      'variables' => array(),
    ),
    'commerce_pos_report_order_details' => array(
      'path' => $path . '/theme',
      'file' => 'commerce_pos_report.theme.inc',
      'template' => 'commerce-pos-report-order-details',
      'variables' => array(
        'order' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_permission().
 */
function commerce_pos_report_permission() {
  return array(
    'view commerce pos reports' => array(
      'title' => t('View Commerce POS Report'),
      'description' => t('View reports provided by Commerce POS Report.'),
    ),
    'administer commerce pos report' => array(
      'title' => t('Administer Commerce POS Report'),
      'description' => t('Perform administration tasks for Commerce POS Report.'),
    ),
  );
}

/**
 * Implements hook_commerce_pos_header_links_alter().
 */
function commerce_pos_report_commerce_pos_header_links_alter(&$links) {
  $links['admin/commerce/pos/reports'] = t('Reports');
}

/**
 * Builds a render array of a summary and POS orders, broken down by price component.
 */
function commerce_pos_report_order_summary($completed_date, $transaction_type, $register_id = 0) {
  $output = array();

  $query = db_select('commerce_pos_transaction', 't');

  $query->fields('ct', array(
    'commerce_order_total_amount',
    'commerce_order_total_currency_code',
    'commerce_order_total_data',
  ));

  $query->join('field_data_commerce_order_total', 'ct', 'ct.entity_id = t.order_id AND ct.entity_type=:commerce_order', array(
    ':commerce_order' => 'commerce_order',
  ));

  $query->where("DATE_FORMAT(FROM_UNIXTIME(t.completed), '%Y-%m-%d') = :completed_date", array(
    ':completed_date' => $completed_date,
  ));

  if ($register_id) {
    $query->condition('t.register_id', $register_id);
  }

  $query->condition('t.type', $transaction_type);

  if ($result = $query->execute()) {
    $prices = array();

    $output['total_orders'] = $result->rowCount();

    foreach ($result as $row) {
      $currency_code = $row->commerce_order_total_currency_code;
      $data = unserialize($row->commerce_order_total_data);
      $amount = $row->commerce_order_total_amount;

      if (!isset($prices[$currency_code])) {
        $prices[$currency_code] = array(
          'name' => 'commerce_total',
          'price' => array(
            'amount' => $amount,
            'currency_code' => $currency_code,
            'data' => array(
              'components' => array(),
            ),
          ),
        );
      }
      else {
        $prices[$currency_code]['price']['amount'] += $amount;
      }

      $price_components = &$prices[$currency_code]['price']['data']['components'];

      foreach ($data['components'] as $component) {
        $component_to_update = FALSE;

        foreach ($price_components as $key => &$price_component) {
          if ($price_component['name'] == $component['name']) {
            $component_to_update = &$price_component;
            break;
          }
        }

        if (!$component_to_update) {
          $price_components[] = $component;
        }
        else {
          $component_to_update['price']['amount'] += $component['price']['amount'];
          unset($component_to_update);
        }
      }
    }

    // Now that we've built our price fields list, we need to theme the
    // output.
    if (!empty($prices)) {
      foreach ($prices as $currency_code => $price) {
        $output['summaries'][$currency_code] = commerce_pos_report_build_price_array($price['price'], $transaction_type);
      }
    }
  }

  return $output;
}

/**
 * Builds a render array of a formatted price with components.
 *
 * Most of this logic was taken from commerce_price_field_formatter_view().
 */
function commerce_pos_report_build_price_array($price, $transaction_type) {
  // Build an array of component display titles and their prices.
  $components = array();
  $weight = 0;

  foreach ($price['data']['components'] as $key => $component) {
    $component_type = commerce_price_component_type_load($component['name']);

    if (empty($components[$component['name']])) {
      $components[$component['name']] = array(
        'title' => check_plain($component_type['display_title']),
        'price' => commerce_price_component_total($price, $component['name']),
        'weight' => $component_type['weight'],
      );

      $weight = max($weight, $component_type['weight']);
    }
  }

  // If there is only a single component and its price equals the field's,
  // then remove it and just show the actual price amount.
  if (count($components) == 1 && in_array('base_price', array_keys($components))) {
    $components = array();
  }

  // Add the actual field value to the array.
  $components['commerce_price_formatted_amount'] = array(
    'title' => t('Total'),
    'price' => $price,
    'weight' => $weight + 1,
  );

  // Allow other modules to alter the components.
  drupal_alter('commerce_price_formatted_components', $components, $price, $entity);

  // Sort the components by weight.
  uasort($components, 'drupal_sort_weight');

  // Format the prices for display.
  foreach ($components as $key => &$component) {
    $component['formatted_price'] = commerce_pos_commerce_currency_format(
      $component['price']['amount'],
      $component['price']['currency_code'],
      $entity
    );
  }

  return array(
    '#theme' => 'commerce_price_formatted_components',
    '#components' => $components,
    '#price' => $price,
  );
}

/**
 * Prepares an array of JavaScript settings that contain instructions on how to format currencies via a JavaScript function call.
 *
 * @param array $currencies
 *   An array of currency codes to provide formatting settings for.
 *
 * @return array
 *   Formatting settings for any requested currencies, key'd by currency code.
 */
function commerce_pos_report_currency_js(array $currencies) {
  $settings = array();

  foreach ($currencies as $currency_code) {
    $settings[$currency_code] = commerce_currency_load($currency_code);
    $settings[$currency_code]['divisor'] = pow(10, $settings[$currency_code]['decimals']);
  }

  return $settings;
}

/**
 * Custom currency formatter function.
 *
 * Most logic taken from commerce_currency_format().
 */
function commerce_pos_report_currency_format($amount, $currency_code, $convert = TRUE) {

  // First load the currency array.
  $currency = commerce_currency_load($currency_code);

  // Then convert the price amount to the currency's major unit decimal value.
  if ($convert == TRUE) {
    $amount = commerce_currency_amount_to_decimal($amount, $currency_code);
  }

  // Format the price as a number.
  $price = number_format(commerce_currency_round(abs($amount), $currency), $currency['decimals'], $currency['decimal_separator'], $currency['thousands_separator']);

  // Establish the replacement values to format this price for its currency.
  $replacements = array(
    '@code_before' => $currency['code_placement'] == 'before' ? $currency['code'] : '',
    '@symbol_before' => $currency['symbol_placement'] == 'before' ? $currency['symbol'] : '',
    '@price' => $price,
    '@symbol_after' => $currency['symbol_placement'] == 'after' ? $currency['symbol'] : '',
    '@code_after' => $currency['code_placement'] == 'after' ? $currency['code'] : '',
    '@negative_before' => $amount < 0 ? '(' : '',
    '@negative_after' => $amount < 0 ? ')' : '',
    '@symbol_spacer' => $currency['symbol_spacer'],
    '@code_spacer' => $currency['code_spacer'],
  );

  return trim(t('@code_before@code_spacer@negative_before@symbol_before@price@negative_after@symbol_spacer@symbol_after@code_spacer@code_after', $replacements));
}

/**
 * Determines if a specific timestamp is before the end of the reporting day.
 */
function commerce_pos_report_before_end_of_day($time = FALSE) {
  $today = strtotime('00:00:00');

  if ($time === FALSE) {
    $time = time();
  }

  if ($time >= $today) {
    return ($time < commerce_pos_report_end_of_day_timestamp());
  }

  return FALSE;
}

/**
 * Retrieves the timestamp for the end of day.
 *
 * @param int|bool $time
 *   (optional) A timestamp to calculate the end of the day for. If this is not
 *   provided, the end of day timestamp will be returned for the current time.
 *
 * @return int
 *   The timestamp for the end of the day.
 */
function commerce_pos_report_end_of_day_timestamp($time = FALSE) {
  $hour = variable_get('commerce_pos_report_end_of_day_hour', 23);
  $minute = variable_get('commerce_pos_report_end_of_day_minute', 59);

  if ($time === FALSE) {
    // Use the current time if no time was provided.
    $time = time();
  }

  return strtotime("$hour:$minute", $time);
}

/**
 * Builds a formatted string of an order's payment types, comma-separated.
 *
 * @param int $order_id
 *   The Commerce order ID.
 *
 * @return string
 *   Comma separated list of payment types for the specified order.
 */
function commerce_pos_report_payment_types($order_id) {
  // Get all the transactions for this order.
  $transaction_ids = commerce_pos_get_order_transactions($order_id);
  $transactions = commerce_payment_transaction_load_multiple($transaction_ids);

  // Now, let's get all the different transaction statuses we have and find the
  // statuses that count towards the total.
  $transaction_statuses = commerce_payment_transaction_statuses();
  foreach ($transaction_statuses as $transaction_status) {
    if ($transaction_status['total'] == TRUE) {
      $successful_statuses[$transaction_status['status']] = $transaction_status['status'];
    }
  }

  // Go through and grab the title of the payment types but strike through all
  // the transactions that didn't count towards the total.
  foreach ($transactions as $transaction) {
    if ($transaction->payment_method != 'commerce_pos_change' && $payment_method = commerce_payment_method_load($transaction->payment_method)) {
      if (!isset($successful_statuses[$transaction->status])) {
        $title = '<strike class="unsuccessful">' . $payment_method['title'] . '</strike>';
      }
      else {
        $title = $payment_method['title'];
      }

      // Now, add it to the payment types.
      $payment_types[] = $title;
    }
  }

  // If no payments were found we are likely dealing with a 0 balance exchange.
  if (empty($payment_types)) {
    $payment_types[] = t('None');
  }

  return implode(', ', $payment_types);
}
