<?php

/**
 * @file
 * Core hooks and utility functions for commerce_pos_discount.
 */

/**
 * Implements hook_commerce_pos_transaction_base_info().
 */
function commerce_pos_discount_commerce_pos_transaction_base_info() {
  return array(
    'commerce_pos_discount_base' => array(
      'class' => 'CommercePosDiscountBase',
      'types' => array(
        CommercePosService::TRANSACTION_TYPE_SALE,
        CommercePosService::TRANSACTION_TYPE_RETURN,
      ),
    ),
  );
}

/**
 * Implements hook_commerce_line_item_type_info().
 */
function commerce_pos_discount_commerce_line_item_type_info() {
  return array(
    'commerce_pos_discount' => array(
      'type' => 'commerce_pos_discount',
      'name' => t('POS discount'),
      'description' => t('Line item for fixed POS discount amounts.'),
      'add_form_submit_value' => t('Add POS discount'),
      'base' => 'commerce_pos_discount_line_item',
    ),
  );
}

/**
 * Determine the discount's line item title.
 *
 * @return string
 *   The line item title.
 */
function commerce_pos_discount_line_item_title() {
  return t('POS discount');
}

/**
 * Implements hook_commerce_line_item_rebase_unit_price().
 */
function commerce_pos_discount_commerce_line_item_rebase_unit_price(&$price, $old_components, $line_item) {
  // Check if any discounts have been applied to a line item and recalculate them
  // as needed.
  foreach ($old_components as $component) {
    if (isset($component['price']['data']['pos_discount_type'])) {
      $discount_type = $component['price']['data']['pos_discount_type'];
      $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $line_item);

      switch ($discount_type) {
        case 'percent':
          $discount_amount = $component['price']['data']['pos_discount_rate'];
          break;

        case 'fixed':
          $discount_amount = $component['price']['amount'] * -1;
          break;
      }

      CommercePosDiscountService::applyDiscount($line_item_wrapper, $discount_type, $discount_amount);

      if ($component = CommercePosDiscountService::getPosDiscountComponent($line_item_wrapper->commerce_unit_price, $component['price']['data']['discount_name'])) {
        $component_name = 'discount|' . CommercePosDiscountService::LINE_ITEM_DISCOUNT_NAME;
        $price['data'] = commerce_price_component_add($price, $component_name, $component['price'], TRUE);
        $price['amount'] += $component['price']['amount'];
      }
    }
  }
}

/**
 * Implements hook_commerce_price_formatted_components_alter().
 */
function commerce_pos_discount_commerce_price_formatted_components_alter(&$components, $price, $entity) {
  if (isset($price['data']['components'])) {
    // Loop into price components and alter the component title if the discount
    // component label is found.
    foreach ($price['data']['components'] as $component) {
      if (!isset($component['price']['data']['pos_discount_component_title'])) {
        continue;
      }
      $components[$component['name']]['title'] = $component['price']['data']['pos_discount_component_title'];
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function commerce_pos_discount_form_alter(&$form, &$form_state, $form_id) {
  if (in_array($form_id, array('commerce_pos_sale', 'commerce_pos_return'))) {
    _commerce_pos_discount_transaction_form_alter($form, $form_state);
  }
}

/**
 * Adds discount functionality to the POS transaction forms.
 */
function _commerce_pos_discount_transaction_form_alter(&$form, &$form_state) {
  $form['#attached']['js'][] = drupal_get_path('module', 'commerce_pos_discount') . '/js/commerce_pos_discount.js';

  if (isset($form['line_items'])) {
    $wrapper_ajax = array(
      'wrapper' => $form_state['wrapper_id'],
      'callback' => 'commerce_pos_discount_wrapper_js',
    );

    foreach (element_children($form['line_items']) as $line_item_id) {
      $line_item_element = &$form['line_items'][$line_item_id];

      $line_item_element['discounts'] = array(
        '#type' => 'container',
        '#id' => 'commerce-pos-discount-wrapper-' . $line_item_id,
        '#attributes' => array(
          'class' => array(
            'commerce-pos-discount-wrapper',
          )
        )
      );

      $line_item_element['discounts']['toggle_discount'] = array(
        '#type' => 'button',
        '#value' => t('Discount'),
        '#line_item_id' => $line_item_id,
        '#element_key' => 'toggle-discount',
        '#name' => 'commerce-pos-discount-toggle-discount-' . $line_item_id,
        '#ajax' => array(
          'wrapper' => 'commerce-pos-discount-wrapper-' . $line_item_id,
          'callback' => 'commerce_pos_discount_add_discount_js',
        ),
      );

      $discount_data = $form_state['transaction']->doAction('getExistingLineItemDiscountAmount', $line_item_id);
      if (!empty($form_state['triggering_element']['#element_key']) && $form_state['triggering_element']['#element_key'] == 'toggle-discount') {
        $line_item_element['discounts']['toggle_discount']['#element_key'] = 'toggle-discount-hide';

        $line_item_element['discounts']['add_discount'] = array(
          '#type' => 'container',
          '#size' => 2,
        );

        $line_item_element['discounts']['add_discount']['#attached']['js'][] = array(
          'type' => 'setting',
          'data' => array(
            'commercePosDiscount' => array(
              'focusInput' => TRUE,
              'lineItemId' => $line_item_id,
            ),
          ),
        );

        $line_item_element['discounts']['add_discount']['description'] = array(
          //'#markup' => t('Discount:'),
        );

        $line_item_element['discounts']['add_discount']['amount'] = array(
          '#type' => 'textfield',
          '#title' => NULL,
          '#size' => 2,
          '#default_value' => $discount_data ? $discount_data['amount'] : NULL,
        );

        $line_item_element['discounts']['add_discount']['percent'] = array(
          '#type' => 'button',
          '#value' => '%',
          '#element_key' => 'add-percent-discount',
          '#line_item_id' => $line_item_id,
          '#name' => 'commerce-pos-discount-percent-discount-' . $line_item_id,
          '#ajax' => $wrapper_ajax,
        );

        $line_item_element['discounts']['add_discount']['fixed'] = array(
          '#type' => 'button',
          '#value' => '$',
          '#element_key' => 'add-fixed-discount',
          '#line_item_id' => $line_item_id,
          '#name' => 'commerce-pos-discount-fixed-discount-' . $line_item_id,
          '#ajax' => $wrapper_ajax,
        );

        if ($discount_data) {
          $line_item_element['discounts']['add_discount'][$discount_data['type']]['#attributes']['class'][] = 'active';
        }
      } else {
        if (!empty($discount_data) && isset($discount_data['amount']) & !empty($discount_data['amount'])) {
          $discount_type_symbol = '';
          if (isset($discount_data['type']) && $discount_data['type'] == 'percent') {
            $discount_type_symbol = '%';
          } else {
            $discount_type_symbol = ' ' . $discount_data['currency_code'];
          }

          $line_item_element['discounts']['discount_description'] = array(
            '#markup' => $discount_data['amount'] . $discount_type_symbol . ' ' . t('Discount Applied'),
            '#prefix' => '<span class="discount-description">',
            '#suffix' => '</span>',
            '#line_item_id' => $line_item_id,
            '#element_key' => 'discount-description',
          );

          $line_item_element['discounts']['remove_discount'] = array(
            '#type' => 'button',
            '#value' => 'remove',
            '#prefix' => ' - ',
            '#element_key' => 'remove-discount',
            '#line_item_id' => $line_item_id,
            '#name' => 'commerce-pos-discount-remove-discount-' . $line_item_id,
            '#ajax' => $wrapper_ajax,
            '#attributes' => array(
              'class' => array('button-link')
            )
          );
        }
      }
    }

    // Add a section for order discounts.
    if (!empty($form['transaction_options']['actions'])) {
      $form['transaction_options']['actions']['discount'] = array(
        '#type' => 'button',
        '#value' => t('Discount'),
        '#element_key' => 'toggle-order-discount',
        '#attributes' => array(
          'class' => array('commerce-pos-transaction-btn'),
        ),
        '#ajax' => array(
          'callback' => 'commerce_pos_discount_order_discount_js',
          'wrapper' => 'commerce-pos-discount-add-order-discount-wrapper',
          'effect' => 'slide',
        ),
      );

      $form['transaction_options']['actions']['add_order_discount'] = array(
        '#type' => 'container',
        '#id' => 'commerce-pos-discount-add-order-discount-wrapper',
      );

      if (!empty($form_state['triggering_element']['#element_key']) && $form_state['triggering_element']['#element_key'] == 'toggle-order-discount') {
        $discount_data = $form_state['transaction']->doAction('getExistingOrderDiscountAmount');

        $form['transaction_options']['actions']['add_order_discount']['amount'] = array(
          '#title' => t('Add Discount to Order'),
          '#type' => 'textfield',
          '#size' => 5,
          '#attributes' => array(
              'autofocus' => 'autofocus',
          ),
          '#default_value' => $discount_data ? $discount_data['amount'] : NULL,
        );

        $form['transaction_options']['actions']['add_order_discount']['percent'] = array(
          '#type' => 'button',
          '#size' => 5,
          '#value' => '%',
          '#ajax' => $wrapper_ajax,
          '#element_key' => 'add-order-percent-discount',
        );

        $form['transaction_options']['actions']['add_order_discount']['fixed'] = array(
          '#type' => 'button',
          '#size' => 5,
          '#value' => '$',
          '#ajax' => $wrapper_ajax,
          '#element_key' => 'add-order-fixed-discount',
        );

        if ($discount_data) {
          $form['transaction_options']['actions']['add_order_discount'][$discount_data['type']]['#attributes']['class'][] = 'active';
        }
      }
    }
  }
}

/**
 * Implements hook_commerce_pos_sale_form_ajax_alter().
 */
function commerce_pos_discount_commerce_pos_sale_form_ajax_alter(&$form_state, $triggering_element) {
  if (!empty($triggering_element['#element_key'])) {
    switch ($triggering_element['#element_key']) {
      case 'add-percent-discount':
      case 'add-fixed-discount':
        $discount_amount = $form_state['values']['line_items'][$triggering_element['#line_item_id']]['discounts']['add_discount']['amount'];

        if ($triggering_element['#element_key'] == 'add-percent-discount') {
          $discount_type = 'percent';
        }
        else {
          $discount_type = 'fixed';
          // Convert the amount into cents, as we expected it to be provided
          // in dollars.
          $discount_amount *= 100;
        }

        $form_state['transaction']->doAction('addLineItemDiscount', $discount_type, $form_state['triggering_element']['#line_item_id'], $discount_amount);
        $form_state['order_updated'] = TRUE;
        break;

      case 'remove-discount':
        $discount_amount = 0;
        $discount_type = 'fixed';

        $form_state['transaction']->doAction('addLineItemDiscount', $discount_type, $form_state['triggering_element']['#line_item_id'], $discount_amount);
        $form_state['order_updated'] = TRUE;
        break;

      case 'add-order-percent-discount':
      case 'add-order-fixed-discount':
        $discount_amount = $form_state['values']['transaction_options']['actions']['add_order_discount']['amount'];

        if ($triggering_element['#element_key'] == 'add-order-percent-discount') {
          $discount_type = 'percent';
        }
        else {
          $discount_type = 'fixed';
          // Convert the amount into cents, as we expected it to be provided
          // in dollars.
          $discount_amount *= 100;
        }

        $form_state['transaction']->doAction('addOrderDiscount', $discount_type, $discount_amount);
        $form_state['order_updated'] = TRUE;

        break;
    }
  }
}

/**
 * AJAX callback for the "Add Discount" buttons.
 */
function commerce_pos_discount_add_discount_js($form, &$form_state) {
  $line_item_id = $form_state['triggering_element']['#line_item_id'];
  return $form['line_items'][$line_item_id]['discounts'];
}

/**
 * AJAX callback for the order discounts section.
 */
function commerce_pos_discount_order_discount_js($form, &$form_state) {
  return $form['transaction_options']['actions']['add_order_discount'];
}

/**
 * AJAX callback to return the entire form wrapper.
 */
function commerce_pos_discount_wrapper_js($form, &$form_state) {
  return $form;
}