<?php

/**
 * @file
 * Main UPC scan file, menu hooks and form alters for using UPC scanner to input text.
 */

/**
 * Implements hook_menu().
 */
function commerce_pos_upc_scan_menu() {
  $items['admin/commerce/config/pos/upc'] = array(
    'title' => 'UPC scanning',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_pos_upc_scan_settings'),
    'access arguments' => array('administer commerce pos'),
    'file' => 'includes/commerce_pos_upc_scan.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_form_alter().
 */
function commerce_pos_upc_scan_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'commerce_pos_sale':
    case 'commerce_pos_return':
      _commerce_pos_upc_scan_transaction_form_alter($form, $form_state);
      break;
  }
}

/**
 * Adds UPC-scanning functionality to the POS transaction forms.
 */
function _commerce_pos_upc_scan_transaction_form_alter(&$form, &$form_state) {
  $form['product_search']['upc'] = array(
    '#type' => 'textfield',
    '#title' => t('Product UPC'),
    '#size' => 60,
    '#ajax' => array(
      'callback' => 'commerce_pos_transaction_wrapper_js',
      'wrapper' => $form_state['wrapper_id'],
    ),
    '#element_key' => 'product-upc',
    '#attributes' => array(
      'class' => array('commerce-pos-upc-scan-upc-field'),
    ),
    '#prefix' => '<div class="element-invisible">',
    '#suffix' => '</div>',
  );

  $form['#attached']['js'][] = drupal_get_path('module', 'commerce_pos_upc_scan') . '/js/commerce_pos_upc_scan.js';
}

/**
 * Implements hook_commerce_pos_sale_form_ajax_alter().
 */
function commerce_pos_upc_scan_commerce_pos_sale_form_ajax_alter(&$form_state, $triggering_element) {
  if ($triggering_element['#element_key'] == 'product-upc' && !empty($triggering_element['#value'])) {
    if ($product_id = commerce_pos_upc_scan_lookup($triggering_element['#value'])) {
      $product = commerce_product_load($product_id);
      $form_state['transaction']->addProduct($product);
      $form_state['order_updated'] = TRUE;
    }
  }

  // Tells the form that the product search field should be focused.
  $form_state['focus_product_input'] = TRUE;
}

/**
 * Attempts to look up a product by its UPC.
 */
function commerce_pos_upc_scan_lookup($upc) {
  if (!empty($upc) && is_numeric($upc) && $upc_field = variable_get('commerce_pos_upc_scan_upc_field', FALSE)) {
    if ($upc_field == 'sku') {
      $query = db_select('commerce_product', 'cp')
        ->fields('cp', array('product_id'))
        ->condition('sku', $upc);
      $product_id = $query->execute()->fetchField();
    }
    else {
      $query = new EntityFieldQuery();
      list($field_name, $value_column_name) = explode('|', $upc_field);
      $query->entityCondition('entity_type', 'commerce_product')
        ->fieldCondition($field_name, $value_column_name, $upc, '=')
        // Run the query as user 1.
        ->addMetaData('account', user_load(1));

      $result = $query->execute();
      if (!empty($result['commerce_product'])) {
        $product_id = array_keys($result['commerce_product'])[0];
      }
    }
  }

  return !empty($product_id) ? $product_id : FALSE;
}
