<?php

/**
 * @file
 */

/**
 * Implements hook_menu().
 */
function commerce_pos_upc_scan_menu() {
  $items['admin/commerce/config/pos/upc'] = array(
    'title' => 'UPC scanning',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_pos_upc_scan_settings'),
    'access arguments' => array('administer commerce pos'),
    'file' => 'includes/commerce_pos_upc_scan.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function commerce_pos_upc_scan_form_commerce_pos_sale_alter(&$form, &$form_state, $form_id) {
  $form['product_search']['upc'] = array(
    '#type' => 'textfield',
    '#title' => t('Product UPC (hide me)'),
    '#size' => 60,
    '#ajax' => array(
      'callback' => 'commerce_pos_sale_wrapper_js',
      'wrapper' => $form_state['wrapper_id'],
      'progress' => array(
        'type' => 'commerce_pos',
      ),
    ),
    '#element_key' => 'product-upc',
    '#attributes' => array(
      'class' => array('commerce-pos-upc-scan-upc-field'),
    ),
  );

  $form['#attached']['js'][] = drupal_get_path('module', 'commerce_pos_upc_scan') . '/js/commerce_pos_upc_scan.js';
}

/**
 * Implements hook_commerce_pos_sale_form_ajax_alter().
 */
function commerce_pos_upc_scan_commerce_pos_sale_form_ajax_alter(&$form_state, $triggering_element) {
  if ($triggering_element['#element_key'] == 'product-upc' && !empty($triggering_element['#value'])) {
    if ($product_id = commerce_pos_upc_scan_lookup($triggering_element['#value'])) {
      $product = commerce_product_load($product_id);
      $form_state['transaction']->addProduct($product);
    }
  }

  // Tells the form that the product search field should be focused.
  $form_state['focus_product_input'] = TRUE;
}

/**
 * Attempts to look up a product by its UPC.
 */
function commerce_pos_upc_scan_lookup($upc) {
  $product_id = NULL;

  if (!empty($upc) && is_numeric($upc) && $upc_field = variable_get('commerce_pos_upc_scan_upc_field', FALSE)) {
    if ($upc_field == 'sku') {
      $query = db_select('commerce_product', 'cp')
        ->fields('cp', array('product_id'))
        ->condition('sku', $upc);
    }
    else {
      $query = db_select('field_data_' . $upc_field, 'f')
        ->fields('f', array('entity_id'))
        ->condition('entity_type', 'commerce_product')
        ->condition($upc_field . '_value', $upc);
    }

    $product_id = $query->execute()->fetchField();
  }

  return $product_id;
}
