<?php

/**
 * @file
 */

/**
 * Implements hook_menu().
 */
function commerce_pos_upc_scan_menu() {
  $items['admin/commerce/config/pos/upc'] = array(
    'title' => 'UPC scanning',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_pos_upc_scan_settings'),
    'access arguments' => array('administer commerce pos'),
    'file' => 'includes/commerce_pos_upc_scan.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_commerce_pos_product_lookup_alter().
 */
function commerce_pos_upc_scan_commerce_pos_product_lookup_alter(&$result, $keywords) {
  if (!empty($keywords) && is_numeric($keywords) && $upc_field = variable_get('commerce_pos_upc_scan_upc_field', FALSE)) {
    if ($upc_field == 'sku') {
      $query = db_select('commerce_product', 'cp')
        ->fields('cp', array('product_id'))
        ->condition('sku', $keywords);
    }
    else {
      $query = db_select('field_data_' . $upc_field, 'f')
        ->fields('f', array('entity_id'))
        ->condition('entity_type', 'commerce_product')
        ->condition($upc_field . '_value', $keywords);
    }

    dpq($query);

    if ($product_id = $query->execute()->fetchField()) {
      $result = $product_id;
    }
  }
}
