<?php

/**
 * @file
 * Hook implementations and related functions.
 */

/**
 * Implements hook_menu().
 */
function commerce_pos_terminal_example_menu() {
  $items['admin/commerce/config/pos/terminal/terminal_example'] = array(
    'title' => 'Terminal Example',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_pos_terminal_example_settings_form'),
    'access arguments' => array('administer commerce pos'),
  );

  return $items;
}

/**
 * Implements hook_commerce_pos_terminal_service_info().
 */
function commerce_pos_terminal_example_commerce_pos_terminal_service_info() {
  $server['commerce_pos_terminal_example'] = array(
    'name' => 'commerce_pos_terminal_example',
    'label' => t('Example Terminal Service'),
    'class' => 'CommercePosTerminalExampleService',
    'file' => drupal_get_path('module', 'commerce_pos_terminal_example') . '/CommercePosTerminalExampleService.php',
    'configure' => 'admin/commerce/config/pos/terminal/terminal_example',
  );

  return $server;
}

/**
 * Form function for the example terminal settings.
 */
function commerce_pos_terminal_example_settings_form(array $form, array $form_state) {
  $form['markup'] = array(
    '#markup' => '<p>' . t('Any even amount will be approved and any odd amount will be rejected.') . '</p>',
  );

  return $form;
}
